package script

const (
	additionKey       = "go-script/addition"
	assignmentKey     = "go-script/assignment"
	callFuncKey       = "go-script/callFunc"
	comparisonKey     = "go-script/comparison"
	doWhileKey        = "go-script/doWhile"
	equalityKey       = "go-script/equality"
	expressionKey     = "go-script/expression"
	forKey            = "go-script/for"
	forRangeKey       = "go-script/forRange"
	funcDecKey        = "go-script/funcDec"
	ifKey             = "go-script/if"
	logicKey          = "go-script/logic"
	multiplicationKey = "go-script/multiplication"
	postincdecKey     = "go-script/postincdec"
	primaryKey        = "go-script/primary"
	repeatKey         = "go-script/repeat"
	returnKey         = "go-script/return"
	scriptKey         = "go-script/script"
	statementsKey     = "go-script/statements"
	statementKey      = "go-script/statement"
	switchKey         = "go-script/switch"
	ternaryKey        = "go-script/ternary"
	tryKey            = "go-script/try"
	unaryKey          = "go-script/unary"
	whileKey          = "go-script/while"
)
